# Generated by Django 3.1.3 on 2020-12-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nutriscore', models.IntegerField()),
                ('image_url', models.URLField()),
                ('categories', models.ManyToManyField(blank=True, related_name='product', to='myapp.Category')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
