# Generated by Django 3.1.3 on 2020-12-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='energy_value',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='fat_100g',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='proteins',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='saturated_fat_100g',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='sugars_100g',
            field=models.CharField(max_length=200),
        ),
    ]
